"""added unique constraint on fullurl

Revision ID: 9d53e10e3648
Revises: e81c4bb5016d
Create Date: 2025-12-08 19:31:55.128823

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d53e10e3648'
down_revision: Union[str, Sequence[str], None] = 'e81c4bb5016d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'short_urls', ['full_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_urls', type_='unique')
    # ### end Alembic commands ###
