version: '3.8'
networks:
  dev:

services:
  frontend:
    build: ./frontend_new
    ports:
      - 5500:5500
    networks:
      - dev

  app:
    build: ./backend
    ports:
      - 8000:8000
    networks:
      - dev

  db:
    image: postgres
    env_file:
      - ./backend/src/.env
    ports:
      - 6000:5432
    volumes:
    - short_url_db_data:/var/lib/postgresql/data
    networks:
      - dev

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - dev
  
  redis_gui:
    image: redis/redisinsight
    ports:
      - 5540:5540
    networks:
      - dev
  
volumes:  # указание глобального тома где-то в папках докера, чтобы не мозолила глаза
  short_url_db_data:

